version: "3.8"
services:
  postgresDB:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_USER: jeuzmaldo     
      POSTGRES_PASSWORD: root        
      POSTGRES_DB: inlaze-backend     
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"